#!/usr/bin/env bash

use "go_to"
set -e

function tests {
  go_to_root
  unit_tests
  static_analysis
}

function unit_tests {
  in_yellow "Running unit tests\n"
  go_to_root
  pytest tests

  in_green "All unit tests passed\n"
}

function static_analysis {
  in_yellow "Running static analysis\n"
  go_to_root
  flake8 .
  in_green "Static analysis passed\n"
}
