#!/usr/bin/env bash

use "go_to"
set -e

function console {
  run_container_with_volume ipython
}

function tests {
  go_to_root
  unit_tests
  static_analysis
}

function unit_tests {
  in_yellow "Running unit tests\n"
  go_to_root
  remove_python_files
  run_container_with_volume pytest tests
  in_green "All unit tests passed\n"
}

function static_analysis {
  in_yellow "Running static analysis\n"
  go_to_root
  run_container_with_volume flake8 .
  in_green "Static analysis passed\n"
}

function remove_python_files() {
  find . -path ./virtual_env -prune -o -name '*.pyc' -print | xargs rm -rf
  find . -path ./virtual_env -prune -o -name '__pycache__' -print | xargs rm -rf
}
