#!/usr/bin/env bash


function build_image {
    docker build . -t nicolastrres/backmeup
}

function run_container_with_volume {
    AWS_ACCESS_KEY_ID=$(aws --profile default configure get aws_access_key_id)
    AWS_SECRET_ACCESS_KEY=$(aws --profile default configure get aws_secret_access_key)


    docker run --rm -it \
        -v $(pwd):/back-me-up \
        -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
        -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
        nicolastrres/backmeup ${@}
}
