#!/usr/bin/env bash
# vim: ft=sh:

use "dev"

SUBCOMMAND_DESC="\t\tDev commands"
SUBCOMMAND_HELP=$(cat <<EOH
s|static-analysis   Run flake8
ut|unit-tests       Run unit tests.
t|tests             Run all tests. (Unit and static analysis)
EOH
)

case ${1} in
  t|tests)
    tests
  ;;

  ut|unit-tests)
    unit_tests
  ;;

  s|static-analysis)
    static_analysis
  ;;

  *)
    if [ ! -z ${1} ]
    then
      in_red "'${1}' not found"
      _help
    fi
esac
