#!/usr/bin/env bash
# vim: ft=sh:

use "dev"

SUBCOMMAND_DESC="\t\tDev commands"
SUBCOMMAND_HELP=$(cat <<EOH
t|tests             Run all tests
EOH
)

case ${1} in
  t|tests)
    tests
  ;;

  *)
    if [ ! -z ${1} ]
    then
      in_red "'${1}' not found"
      _help
    fi
esac
